<a href="https://colab.research.google.com/github/kash03cow/Authentication-Security/blob/main/Copy_of_keystroke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('keystroke.csv')
y=dataset.iloc[:,0]
x=dataset.iloc[:,1:]
# for i in range(1,int(dataset.shape[1])):
#   if(i%4==1):
#     b=dataset.iloc[:,i]
#     # np.hstack((x,dataset.iloc[:,i]))
#     np.c_[x,b]



In [3]:
x.head()

sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  DD.t.i  \
0             1    1    0.1491       0.3979       0.2488  0.1069  0.1674   
1             1    2    0.1111       0.3451       0.2340  0.0694  0.1283   
2             1    3    0.1328       0.2072       0.0744  0.0731  0.1291   
3             1    4    0.1291       0.2515       0.1224  0.1059  0.2495   
4             1    5    0.1249       0.2317       0.1068  0.0895  0.1676   

   UD.t.i     H.i  DD.i.e  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.0605  0.1169  0.2212  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.0589  0.0908  0.1357  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.0560  0.0821  0.1542  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.1436  0.1040  0.2038  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.0781  0.0903  0.1589  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 33 columns]

In [4]:
# t=x.shape
# t[1]
# for i in range(3,t[1]-2):
#   if(i%2==0):
#     x.drop(x.columns[i],axis=1,inplace=True)

In [5]:
x.head()

sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  DD.t.i  \
0             1    1    0.1491       0.3979       0.2488  0.1069  0.1674   
1             1    2    0.1111       0.3451       0.2340  0.0694  0.1283   
2             1    3    0.1328       0.2072       0.0744  0.0731  0.1291   
3             1    4    0.1291       0.2515       0.1224  0.1059  0.2495   
4             1    5    0.1249       0.2317       0.1068  0.0895  0.1676   

   UD.t.i     H.i  DD.i.e  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
0  0.0605  0.1169  0.2212  ...  0.1349  0.1484  0.0135  0.0932  0.3515   
1  0.0589  0.0908  0.1357  ...  0.1412  0.2558  0.1146  0.1146  0.2642   
2  0.0560  0.0821  0.1542  ...  0.1621  0.2332  0.0711  0.1172  0.2705   
3  0.1436  0.1040  0.2038  ...  0.1457  0.1629  0.0172  0.0866  0.2341   
4  0.0781  0.0903  0.1589  ...  0.1312  0.1582  0.0270  0.0884  0.2517   

   UD.n.l     H.l  DD.l.Return  UD.l.Return  H.Return  
0  0.2583  0.1338       0.3509       0.2171    0.0742  
1  0.1496  0.0839       0.2756       0.1917    0.0747  
2  0.1533  0.1085       0.2847       0.1762    0.0945  
3  0.1475  0.0845       0.3232       0.2387    0.0813  
4  0.1633  0.0903       0.2517       0.1614    0.0818  

[5 rows x 33 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [7]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=23)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=23)

In [9]:
print(X_train)


       sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  DD.t.i  \
18317             7   18    0.0541       0.5762       0.5221  0.0784  0.0768   
10759             8   10    0.1246       0.1131      -0.0115  0.1024  0.2113   
13665             2   16    0.1042       0.3707       0.2665  0.1395  0.0936   
17691             2   42    0.1124       0.1682       0.0558  0.0660  0.1180   
8401              1    2    0.1093       0.4998       0.3905  0.0895  0.6498   
...             ...  ...       ...          ...          ...     ...     ...   
10955             4    6    0.1029       0.3109       0.2080  0.1536  0.1087   
17289             2   40    0.0828       0.1539       0.0711  0.0757  0.1525   
5192              8   43    0.0694       0.1123       0.0429  0.0481  0.1408   
12172             4   23    0.0433       0.7183       0.6750  0.0617  0.1730   
235               5   36    0.0929       0.1153       0.0224  0.0813  0.1563   

       UD.t.i     H.i  DD.i.e  ...     

In [10]:
y_rf_pred= classifier.predict(x_test)
print(y_rf_pred)

[37  1  2 ... 37 27 42]


In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score
conf= confusion_matrix(y_rf_pred,y_test)
print(conf)
accuracy_score(y_test,y_rf_pred)

[[40  0  0 ...  0  1  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 34 ...  0  1  0]
 ...
 [ 0  0  0 ... 40  1  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  1  0 38]]


0.9372549019607843

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
x_test = sc.transform(x_test)

In [13]:
from sklearn.svm import SVC
clf= SVC(kernel='rbf',random_state=23)
clf.fit(X_train,y_train)

SVC(random_state=23)

In [14]:
# from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = clf.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[37 37]
 [ 1  1]
 [ 2  2]
 ...
 [37 37]
 [27 27]
 [42 42]]
[[40  0  0 ...  0  0  0]
 [ 0 34  0 ...  0  1  0]
 [ 0  0 34 ...  0  0  0]
 ...
 [ 0  0  0 ... 40  0  0]
 [ 0  0  0 ...  0 31  1]
 [ 0  0  0 ...  0  0 37]]


0.9073529411764706